name: Upload to TestFlight
 
on:
  push:
    branches:
    - main 
  # pull_request:
  #   branches:
  #     - main


jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app/
      - name: Show Xcode version
        run: xcodebuild -version
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install and update Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/watchman.rb" > .github/brew-formulae
          sudo rm '/usr/local/bin/2to3'
          brew link --overwrite python@3.9
          brew upgrade

      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/foo--*
            ~/Library/Caches/Homebrew/downloads/*--foo-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-

      - name: Setup watchman
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install watchman
          sudo gem update

      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: Install Cocos Pods
        run: |
          yarn install
          cd ios
          sudo gem install cocoapods && pod install

      - name: "#️⃣ Update Build Number"
        id: buildnumber
        uses: poad/xcode-build-number-auto-update@v1
        with:
          path: ./ios/ReactNativeAppSample/Info.plist
          new-number: ${{ github.run_number }}

      - name: Import iOS CodeSign Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        id: develop-certificate
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: Import iOS CodeSign Certificates (for distibution)
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          create-keychain: false
          keychain-password: ${{ steps.develop-certificate.outputs.keychain-password }}
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: Download Provisioning Profiles
        uses: apple-actions/download-provisioning-profiles@v1
        with: 
          bundle-id: 'com.github.poad.*'
          profile-type: 'IOS_APP_ADHOC'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Download Provisioning Profiles (for distibution)
        uses: apple-actions/download-provisioning-profiles@v1
        with: 
          bundle-id: 'com.github.poad.*'
          profile-type: 'IOS_APP_ADHOC'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Generate exportOptions.plist
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          PROVISONING_PROFILE_UUID: ${{ secrets.PROVISONING_PROFILE_UUID }}
        run: |
          touch ios/exportOptions.plist
          cat exportOptions.plist.template | sed -e s/\$\{PROVISONING_PROFILE_UUID\}/${PROVISONING_PROFILE_UUID}/g | sed -e s/\$\{TEAM_ID\}/${TEAM_ID}/g >> ios/exportOptions.plist
          cat ios/exportOptions.plist

      - name: Test
        run: yarn test

      - name: Cache Xcode archive
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-archive-cache-${{ hashFiles('**/ios/ReactNativeAppSample.xcarchive') }}
          restore-keys: |
            ${{ runner.OS }}-archive-cache-

      - name: iOS app build
        env:
          RCT_NO_LAUNCH_PACKAGER: 1
        run: |
          cd ios
          xcodebuild -workspace ReactNativeAppSample.xcworkspace -scheme ReactNativeAppSample archive -archivePath ReactNativeAppSample.xcarchive
          xcodebuild -exportArchive -archivePath ./ReactNativeAppSample.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist

      - name: Lookup IPA file
        run: echo "ipa_file_path=$(pwd)/$(ls ./flutter_app_example/ios/build/*.ipa)" >> $GITHUB_ENV

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: ${{ env.ipa_file_path }}
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
